//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fs24bot3.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fs24bot3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&apos;utf-8&apos;&gt;
        ///  &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge&apos;&gt;
        ///  &lt;title&gt;FS24BOT: Help&lt;/title&gt;
        ///  &lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1&apos;&gt;
        ///  &lt;style&gt;
        ///    body {
        ///      margin: 0px;
        ///      padding: 0px;
        ///    }
        ///
        ///    a {
        ///      text-decoration: none;
        ///      color: #86796b;
        ///    }
        ///
        ///    a:hover {
        ///      color: #3A405A;
        ///    }
        ///
        ///    .menu {
        ///      background-color: #fbf1c7;
        ///    }
        ///
        ///    .menuItem {
        ///      padding-left: 1em;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help
        {
            get
            {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&apos;utf-8&apos;&gt;
        ///  &lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge&apos;&gt;
        ///  &lt;title&gt;FS24BOT: Shop&lt;/title&gt;
        ///  &lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1&apos;&gt;
        ///  &lt;style&gt;
        ///    body {
        ///      margin: 0px;
        ///      padding: 0px;
        ///    }
        ///
        ///    a {
        ///      text-decoration: none;
        ///      color: #86796b;
        ///    }
        ///    
        ///    h1 {
        ///      font-size: 70px;
        ///    }
        ///
        ///    a:hover {
        ///      color: #3A405A;
        ///    }
        ///
        ///    .menu {
        ///      background-color: #fbf1c7;
        ///    } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shop
        {
            get
            {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to a
        ///about
        ///all
        ///am
        ///an
        ///and
        ///any
        ///are
        ///as
        ///at
        ///be
        ///been
        ///but
        ///by
        ///can
        ///could
        ///do
        ///for
        ///from
        ///has
        ///have
        ///i
        ///if
        ///in
        ///is
        ///it
        ///me
        ///my
        ///no
        ///not
        ///of
        ///on
        ///one
        ///or
        ///so
        ///that
        ///the
        ///them
        ///there
        ///they
        ///this
        ///to
        ///was
        ///we
        ///what
        ///which
        ///will
        ///with
        ///would
        ///you
        ///а
        ///будем
        ///будет
        ///будете
        ///будешь
        ///буду
        ///будут
        ///будучи
        ///будь
        ///блин
        ///будьте
        ///бы
        ///был
        ///была
        ///были
        ///было
        ///быть
        ///в
        ///вам
        ///вами
        ///вас
        ///весь
        ///во
        ///вот
        ///все
        ///всё
        ///всего
        ///всей
        ///всем
        ///всём
        ///всеми
        ///всему
        ///всех
        ///всею
        ///всея
        ///всю
        ///вся
        ///вы
        ///да
        ///для
        ///до
        ///его
        ///едим
        ///едят
        ///ее
        ///её
        ///ей
        ///ел [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stopwords
        {
            get
            {
                return ResourceManager.GetString("stopwords", resourceCulture);
            }
        }

        internal static string adjectives
        {
            get
            {
                return ResourceManager.GetString("adjectives", resourceCulture);
            }
        }

        internal static string nouns
        {
            get
            {
                return ResourceManager.GetString("nouns", resourceCulture);
            }
        }
    }
}
